services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  WapplerSystems\FeRegistration\:
    resource: '../Classes/*'


  WapplerSystems\FeRegistration\Service\Mailer:
    public: true


