prototypes:
  standard:
    finishersDefinition:
      RestoreFormValues:
        implementationClassName: WapplerSystems\FeRegistration\Domain\Finishers\RestoreFormValuesFinisher
        formEditor:
          iconIdentifier: form-finisher
          label: 'Restore form values after confirmation'

